version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - mynetwork
    
  postgres:
    image: postgres
    volumes:
      - mydata:/var/lib/postgresql/datadb
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      mynetwork:
        aliases:
          - new_db
          - dev_db

volumes:
  mydata:
        
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28
