---
- name: Create a user, set up SSH key authentication, disable password authentication, and create a directory
  hosts: "all"
  become: yes
  
  vars:
    user_name: rizvan3
    key_file: '/home/rizvan/.ssh/id_rsa.pub'
    directory_name: directory
    directory_owner: rizvan3
    directory_group: rizvan3
    directory_mode: "755"
  
  tasks:
  
  - name: Create the user
    user:
      name: "{{ user_name }}"
      createhome: yes
      shell: /bin/bash

  - user:
      name: "{{ user_name }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "{{ lookup('file', key_file) }}"
  
  - name: Create the directory
    file:
      path: "/opt/{{ directory_name }}"
      state: directory
      owner: "{{ directory_owner }}"
      group: "{{ directory_group }}"
      mode: "{{ directory_mode }}"
